repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml", "bodocache/planner/api.py"]
        additional_dependencies:
          - types-PyYAML>=6.0.12
        pass_filenames: false
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-q", "-r", "bodocache"]
        pass_filenames: false
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.23.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
